name: CI - Master - Generate docs

on:
  push:
    branches:
      - master
    paths:
      - 'website/docs/**'

jobs:
  build:
    name: Generate web
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate docs from files
      run: |
        cd docs
        ./generate.sh > usage.md

    - name: Commit updated docs
      run: |
        git config user.email "teamcloudnative-noreply@sysdig.com"
        git config user.name "Github Actions"
        git add docs

        git commit -m "docs: Automatic documentation update"
        git push origin HEAD:${GITHUB_REF}

